name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: lpmec
          extra-packages: any::testthat
      - name: Install package
        run: R CMD INSTALL lpmec
      - name: Run tests
        run: Rscript -e 'library(lpmec); testthat::test_dir("tests/testthat")'
